/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    MockToken1: {
      address: "0x290F385a98e707275366648817403E415a808a63",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
            {
              name: "initialSupply",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "allowance",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transfer",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ERC20InsufficientAllowance",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "allowance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InsufficientBalance",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidApprover",
          inputs: [
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidReceiver",
          inputs: [
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSender",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSpender",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {
        allowance: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        approve: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        balanceOf: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        decimals: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        name: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        symbol: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        totalSupply: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        transfer: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        transferFrom: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
      },
    },
    MockToken2: {
      address: "0x3D10F2021266d0d83090046fDF0b8790779C2A82",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
            {
              name: "initialSupply",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "allowance",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transfer",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ERC20InsufficientAllowance",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "allowance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InsufficientBalance",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidApprover",
          inputs: [
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidReceiver",
          inputs: [
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSender",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSpender",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {
        allowance: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        approve: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        balanceOf: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        decimals: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        name: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        symbol: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        totalSupply: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        transfer: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        transferFrom: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
      },
    },
    MockVeBAL: {
      address: "0xd213c4cC9Bd38bc7dC8877e5f53955c3E5F5F416",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
            {
              name: "initialSupply",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "allowance",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transfer",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ERC20InsufficientAllowance",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "allowance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InsufficientBalance",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidApprover",
          inputs: [
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidReceiver",
          inputs: [
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSender",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSpender",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {
        allowance: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        approve: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        balanceOf: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        decimals: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        name: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        symbol: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        totalSupply: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        transfer: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
        transferFrom: "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol",
      },
    },
    ConstantSumFactory: {
      address: "0x90e1d376163cb8287ae4fF1f15CbD4F594DF6201",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "vault",
              type: "address",
              internalType: "contract IVault",
            },
            {
              name: "pauseWindowDuration",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "create",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
            {
              name: "salt",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "tokens",
              type: "tuple[]",
              internalType: "struct TokenConfig[]",
              components: [
                {
                  name: "token",
                  type: "address",
                  internalType: "contract IERC20",
                },
                {
                  name: "tokenType",
                  type: "uint8",
                  internalType: "enum TokenType",
                },
                {
                  name: "rateProvider",
                  type: "address",
                  internalType: "contract IRateProvider",
                },
                {
                  name: "paysYieldFees",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
            {
              name: "swapFeePercentage",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "protocolFeeExempt",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "roleAccounts",
              type: "tuple",
              internalType: "struct PoolRoleAccounts",
              components: [
                {
                  name: "pauseManager",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "swapFeeManager",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "poolCreator",
                  type: "address",
                  internalType: "address",
                },
              ],
            },
            {
              name: "poolHooksContract",
              type: "address",
              internalType: "address",
            },
            {
              name: "liquidityManagement",
              type: "tuple",
              internalType: "struct LiquidityManagement",
              components: [
                {
                  name: "disableUnbalancedLiquidity",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableAddLiquidityCustom",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableRemoveLiquidityCustom",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableDonation",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          outputs: [
            {
              name: "pool",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "disable",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getActionId",
          inputs: [
            {
              name: "selector",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getAuthorizer",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IAuthorizer",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDefaultLiquidityManagement",
          inputs: [],
          outputs: [
            {
              name: "liquidityManagement",
              type: "tuple",
              internalType: "struct LiquidityManagement",
              components: [
                {
                  name: "disableUnbalancedLiquidity",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableAddLiquidityCustom",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableRemoveLiquidityCustom",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableDonation",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "getDefaultPoolHooksContract",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "getDeploymentAddress",
          inputs: [
            {
              name: "salt",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNewPoolPauseWindowEndTime",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getOriginalPauseWindowEndTime",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPauseWindowDuration",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getVault",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IVault",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isDisabled",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isPoolFromFactory",
          inputs: [
            {
              name: "pool",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "FactoryDisabled",
          inputs: [],
          anonymous: false,
        },
        {
          type: "event",
          name: "PoolCreated",
          inputs: [
            {
              name: "pool",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "Disabled",
          inputs: [],
        },
        {
          type: "error",
          name: "PoolPauseWindowDurationOverflow",
          inputs: [],
        },
        {
          type: "error",
          name: "SenderNotAllowed",
          inputs: [],
        },
        {
          type: "error",
          name: "StandardPoolWithCreator",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
    },
    ConstantProductFactory: {
      address: "0x98Ae3884f844035F02d1eEbE94E54C25bCb53794",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "vault",
              type: "address",
              internalType: "contract IVault",
            },
            {
              name: "pauseWindowDuration",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "create",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
            {
              name: "salt",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "tokens",
              type: "tuple[]",
              internalType: "struct TokenConfig[]",
              components: [
                {
                  name: "token",
                  type: "address",
                  internalType: "contract IERC20",
                },
                {
                  name: "tokenType",
                  type: "uint8",
                  internalType: "enum TokenType",
                },
                {
                  name: "rateProvider",
                  type: "address",
                  internalType: "contract IRateProvider",
                },
                {
                  name: "paysYieldFees",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
            {
              name: "swapFeePercentage",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "protocolFeeExempt",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "roleAccounts",
              type: "tuple",
              internalType: "struct PoolRoleAccounts",
              components: [
                {
                  name: "pauseManager",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "swapFeeManager",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "poolCreator",
                  type: "address",
                  internalType: "address",
                },
              ],
            },
            {
              name: "poolHooksContract",
              type: "address",
              internalType: "address",
            },
            {
              name: "liquidityManagement",
              type: "tuple",
              internalType: "struct LiquidityManagement",
              components: [
                {
                  name: "disableUnbalancedLiquidity",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableAddLiquidityCustom",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableRemoveLiquidityCustom",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableDonation",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          outputs: [
            {
              name: "pool",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "disable",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getActionId",
          inputs: [
            {
              name: "selector",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getAuthorizer",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IAuthorizer",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDefaultLiquidityManagement",
          inputs: [],
          outputs: [
            {
              name: "liquidityManagement",
              type: "tuple",
              internalType: "struct LiquidityManagement",
              components: [
                {
                  name: "disableUnbalancedLiquidity",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableAddLiquidityCustom",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableRemoveLiquidityCustom",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableDonation",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "getDefaultPoolHooksContract",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "getDeploymentAddress",
          inputs: [
            {
              name: "salt",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNewPoolPauseWindowEndTime",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getOriginalPauseWindowEndTime",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPauseWindowDuration",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getVault",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IVault",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isDisabled",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isPoolFromFactory",
          inputs: [
            {
              name: "pool",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "FactoryDisabled",
          inputs: [],
          anonymous: false,
        },
        {
          type: "event",
          name: "PoolCreated",
          inputs: [
            {
              name: "pool",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "Disabled",
          inputs: [],
        },
        {
          type: "error",
          name: "PoolPauseWindowDurationOverflow",
          inputs: [],
        },
        {
          type: "error",
          name: "SenderNotAllowed",
          inputs: [],
        },
        {
          type: "error",
          name: "StandardPoolWithCreator",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
    },
    VeBALFeeDiscountHook: {
      address: "0x7798AD4e898a948FFCf426fb2aAdffbD01087085",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "vault",
              type: "address",
              internalType: "contract IVault",
            },
            {
              name: "allowedFactory",
              type: "address",
              internalType: "address",
            },
            {
              name: "trustedRouter",
              type: "address",
              internalType: "address",
            },
            {
              name: "veBAL",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getHookFlags",
          inputs: [],
          outputs: [
            {
              name: "hookFlags",
              type: "tuple",
              internalType: "struct HookFlags",
              components: [
                {
                  name: "enableHookAdjustedAmounts",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "shouldCallBeforeInitialize",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "shouldCallAfterInitialize",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "shouldCallComputeDynamicSwapFee",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "shouldCallBeforeSwap",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "shouldCallAfterSwap",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "shouldCallBeforeAddLiquidity",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "shouldCallAfterAddLiquidity",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "shouldCallBeforeRemoveLiquidity",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "shouldCallAfterRemoveLiquidity",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "onAfterAddLiquidity",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint8",
              internalType: "enum AddLiquidityKind",
            },
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "amountsInRaw",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "onAfterInitialize",
          inputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "onAfterRemoveLiquidity",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint8",
              internalType: "enum RemoveLiquidityKind",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "amountsOutRaw",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "onAfterSwap",
          inputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct AfterSwapParams",
              components: [
                {
                  name: "kind",
                  type: "uint8",
                  internalType: "enum SwapKind",
                },
                {
                  name: "tokenIn",
                  type: "address",
                  internalType: "contract IERC20",
                },
                {
                  name: "tokenOut",
                  type: "address",
                  internalType: "contract IERC20",
                },
                {
                  name: "amountInScaled18",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "amountOutScaled18",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "tokenInBalanceScaled18",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "tokenOutBalanceScaled18",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "amountCalculatedScaled18",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "amountCalculatedRaw",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "router",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "pool",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "userData",
                  type: "bytes",
                  internalType: "bytes",
                },
              ],
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "onBeforeAddLiquidity",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint8",
              internalType: "enum AddLiquidityKind",
            },
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "onBeforeInitialize",
          inputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "onBeforeRemoveLiquidity",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint8",
              internalType: "enum RemoveLiquidityKind",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "onBeforeSwap",
          inputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct PoolSwapParams",
              components: [
                {
                  name: "kind",
                  type: "uint8",
                  internalType: "enum SwapKind",
                },
                {
                  name: "amountGivenScaled18",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "balancesScaled18",
                  type: "uint256[]",
                  internalType: "uint256[]",
                },
                {
                  name: "indexIn",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "indexOut",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "router",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "userData",
                  type: "bytes",
                  internalType: "bytes",
                },
              ],
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "onComputeDynamicSwapFeePercentage",
          inputs: [
            {
              name: "params",
              type: "tuple",
              internalType: "struct PoolSwapParams",
              components: [
                {
                  name: "kind",
                  type: "uint8",
                  internalType: "enum SwapKind",
                },
                {
                  name: "amountGivenScaled18",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "balancesScaled18",
                  type: "uint256[]",
                  internalType: "uint256[]",
                },
                {
                  name: "indexIn",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "indexOut",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "router",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "userData",
                  type: "bytes",
                  internalType: "bytes",
                },
              ],
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "staticSwapFeePercentage",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "success",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "dynamicSwapFee",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "onRegister",
          inputs: [
            {
              name: "factory",
              type: "address",
              internalType: "address",
            },
            {
              name: "pool",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "tuple[]",
              internalType: "struct TokenConfig[]",
              components: [
                {
                  name: "token",
                  type: "address",
                  internalType: "contract IERC20",
                },
                {
                  name: "tokenType",
                  type: "uint8",
                  internalType: "enum TokenType",
                },
                {
                  name: "rateProvider",
                  type: "address",
                  internalType: "contract IRateProvider",
                },
                {
                  name: "paysYieldFees",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
            {
              name: "",
              type: "tuple",
              internalType: "struct LiquidityManagement",
              components: [
                {
                  name: "disableUnbalancedLiquidity",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableAddLiquidityCustom",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableRemoveLiquidityCustom",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "enableDonation",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
